# Generated by Django 4.2.7 on 2025-09-17 22:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0003_photo_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название лицензии')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полные условия')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='Множитель цены')),
                ('allowed_usage', models.TextField(blank=True, verbose_name='Разрешённое использование')),
                ('assets_limit', models.CharField(blank=True, max_length=120, verbose_name='Ограничения по тиражу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Тип лицензии',
                'verbose_name_plural': 'Типы лицензий',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Имя и фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Компания')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Черновик'), ('awaiting_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='awaiting_payment', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма')),
                ('payment_reference', models.CharField(blank=True, max_length=120, verbose_name='Номер платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.licensetype', verbose_name='Лицензия')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Заказ')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='gallery.photo', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
    ]
