# Generated by Django 4.2.7 on 2025-09-17 22:31

from decimal import Decimal

from django.db import migrations


def seed_licenses(apps, schema_editor):
    LicenseType = apps.get_model('store', 'LicenseType')

    presets = [
        {
            'name': 'Стандартная лицензия',
            'slug': 'standard',
            'short_description': 'Коммерческое и редакционное использование до 500k показов',
            'description': 'Подходит для веб-сайтов, соцсетей, презентаций и печати малым тиражом (до 500 000 экземпляров).',
            'allowed_usage': 'Digital, print (до 500 000 копий), social media, внутренние материалы.',
            'assets_limit': 'Тираж до 500 000',
            'price_multiplier': Decimal('1.0'),
        },
        {
            'name': 'Расширенная лицензия',
            'slug': 'enhanced',
            'short_description': 'Расширенное коммерческое использование до 5 млн показов',
            'description': 'Включает использование в товарах на продажу, наружной рекламе и крупных печатных тиражах (до 5 000 000).',
            'allowed_usage': 'Все из Стандартной + мерч, упаковка, наружная реклама.',
            'assets_limit': 'Тираж до 5 000 000',
            'price_multiplier': Decimal('2.5'),
        },
        {
            'name': 'Неограниченная лицензия',
            'slug': 'unlimited',
            'short_description': 'Максимальные права для крупных кампаний и перепродажи',
            'description': 'Неограниченные тиражи и дистрибуция, разрешено использование в шаблонах и продуктах на перепродажу.',
            'allowed_usage': 'Все права, включая перепродажу контента как части продукта.',
            'assets_limit': 'Неограничено',
            'price_multiplier': Decimal('5.0'),
        },
    ]

    for index, data in enumerate(presets):
        LicenseType.objects.update_or_create(
            slug=data['slug'],
            defaults={
                'name': data['name'],
                'short_description': data['short_description'],
                'description': data['description'],
                'allowed_usage': data['allowed_usage'],
                'assets_limit': data['assets_limit'],
                'price_multiplier': data['price_multiplier'],
                'sort_order': index,
                'is_active': True,
            }
        )


def unseed_licenses(apps, schema_editor):
    LicenseType = apps.get_model('store', 'LicenseType')
    LicenseType.objects.filter(slug__in=['standard', 'enhanced', 'unlimited']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_licenses, unseed_licenses),
    ]
