# Generated by Django 4.2.7 on 2025-09-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Одобрено'),
        ),
    ]
