# Generated by Django 4.2.7 on 2025-09-17 22:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_approve_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8, verbose_name='Базовая цена, $'),
        ),
    ]
