# Generated by Django 4.2.7 on 2025-09-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA256 хеш файла'),
        ),
    ]
