# Generated by Django 4.2.7 on 2025-09-14 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Местоположение')),
                ('total_photos', models.IntegerField(default=0, verbose_name='Всего фотографий')),
                ('total_views', models.IntegerField(default=0, verbose_name='Всего просмотров')),
                ('total_downloads', models.IntegerField(default=0, verbose_name='Всего загрузок')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('public_profile', models.BooleanField(default=True, verbose_name='Публичный профиль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
