# Generated by Django 4.2.7 on 2025-09-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_contributor',
            field=models.BooleanField(default=False, verbose_name='Является автором'),
        ),
    ]
